# Generated by Django 5.2.12 on 2026-03-22 00:00

import apps.therapists.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("therapists", "0002_therapistprofile_bio"),
    ]

    operations = [
        migrations.AddField(
            model_name="therapistprofile",
            name="profile_image",
            field=models.ImageField(
                blank=True,
                upload_to=apps.therapists.models.therapist_profile_image_upload_to,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpg", "jpeg", "png", "webp"]
                    )
                ],
            ),
        ),
    ]
