# Generated by Django 5.2.11 on 2026-03-22 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("therapists", "0003_therapistprofile_profile_image"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="therapistavailability",
            new_name="therapists__start_t_b63cf4_idx",
            old_name="therapists__start_t_bc945c_idx",
        ),
        migrations.RenameIndex(
            model_name="therapistavailability",
            new_name="therapists__is_avai_44f59d_idx",
            old_name="therapists__is_avai_43c4fc_idx",
        ),
    ]
