# Generated by Django 5.2.12 on 2026-04-19 05:09

import decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therapists', '0006_rename_therapists__clinic__97eba9_idx_therapists__clinic__7a8f3d_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='therapistprofile',
            name='commission_rate',
            field=models.DecimalField(decimal_places=4, default=decimal.Decimal('0.10'), max_digits=5),
        ),
        migrations.AddField(
            model_name='therapistprofile',
            name='commission_tier',
            field=models.CharField(default='Starter', max_length=100),
        ),
        migrations.AddField(
            model_name='therapistprofile',
            name='completed_sessions',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='therapistprofile',
            name='total_earnings',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.CreateModel(
            name='TherapistCommissionRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tier_name', models.CharField(max_length=100, unique=True)),
                ('min_sessions', models.PositiveIntegerField(default=0)),
                ('max_sessions', models.PositiveIntegerField(blank=True, null=True)),
                ('commission_rate', models.DecimalField(decimal_places=4, max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('min_sessions', 'id'),
                'indexes': [models.Index(fields=['is_active', 'min_sessions'], name='therapists__is_acti_4173a8_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('max_sessions__isnull', True), ('max_sessions__gte', models.F('min_sessions')), _connector='OR'), name='commission_rule_max_after_min')],
            },
        ),
    ]
