# Generated by Django 5.2.12 on 2026-04-05 13:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0006_appointment_meeting_fields'),
        ('packages', '0001_initial'),
        ('therapists', '0006_rename_therapists__clinic__97eba9_idx_therapists__clinic__7a8f3d_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='booking_payment_type',
            field=models.CharField(choices=[('single', 'Single'), ('package', 'Package')], default='single', max_length=20),
        ),
        migrations.AddField(
            model_name='appointment',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='packages.usersubscription'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='subscription_credit_consumed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='subscription_credit_restored_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['booking_payment_type'], name='appointment_booking_8a380e_idx'),
        ),
    ]
