# Generated by Django 5.2.12 on 2026-04-05 13:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PackagePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('session_credits', models.PositiveSmallIntegerField()),
                ('duration_days', models.PositiveSmallIntegerField(default=30)),
                ('price_amount', models.PositiveIntegerField(help_text='Plan price stored in paisa for Khalti.')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('price_amount', 'id'),
                'indexes': [models.Index(fields=['is_active'], name='packages_pa_is_acti_ddcb4c_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending_payment', 'Pending payment'), ('active', 'Active'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='pending_payment', max_length=20)),
                ('total_credits', models.PositiveSmallIntegerField(default=0)),
                ('remaining_credits', models.PositiveSmallIntegerField(default=0)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('payment_status', models.CharField(choices=[('unpaid', 'Unpaid'), ('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('expired', 'Expired'), ('refunded', 'Refunded')], default='unpaid', max_length=20)),
                ('payment_provider', models.CharField(blank=True, max_length=30, null=True)),
                ('paid_amount', models.PositiveIntegerField(default=0)),
                ('khalti_pidx', models.CharField(blank=True, max_length=255, null=True)),
                ('payment_transaction_id', models.CharField(blank=True, max_length=255, null=True)),
                ('payment_initiated_at', models.DateTimeField(blank=True, null=True)),
                ('payment_verified_at', models.DateTimeField(blank=True, null=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='packages.packageplan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at', '-id'),
                'indexes': [models.Index(fields=['user', 'status'], name='packages_us_user_id_d17308_idx'), models.Index(fields=['expires_at'], name='packages_us_expires_8adcb9_idx'), models.Index(fields=['khalti_pidx'], name='packages_us_khalti__0cdb2e_idx')],
            },
        ),
    ]
