# Generated by Django 5.2.12 on 2026-03-14 08:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MoodEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entry_date', models.DateField()),
                ('mood', models.CharField(choices=[('very_low', 'Very low'), ('low', 'Low'), ('neutral', 'Neutral'), ('good', 'Good'), ('excellent', 'Excellent')], max_length=20)),
                ('stress_level', models.PositiveSmallIntegerField(default=1)),
                ('energy_level', models.PositiveSmallIntegerField(default=1)),
                ('notes', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mood_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-entry_date',),
                'constraints': [models.UniqueConstraint(fields=('user', 'entry_date'), name='unique_mood_entry_per_day'), models.CheckConstraint(condition=models.Q(('stress_level__gte', 1), ('stress_level__lte', 5)), name='stress_level_range'), models.CheckConstraint(condition=models.Q(('energy_level__gte', 1), ('energy_level__lte', 5)), name='energy_level_range')],
            },
        ),
    ]
